// This file was auto-generated by Fern from our API Definition.

import type * as FernAutopilotTestApi from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreateMovieRequest: core.serialization.ObjectSchema<
    serializers.CreateMovieRequest.Raw,
    FernAutopilotTestApi.CreateMovieRequest
> = core.serialization.object({
    title: core.serialization.string(),
    rating: core.serialization.number(),
    moreMetadata: core.serialization.property("more_metadata", core.serialization.number()),
    rank: core.serialization.number(),
});

export declare namespace CreateMovieRequest {
    export interface Raw {
        title: string;
        rating: number;
        more_metadata: number;
        rank: number;
    }
}
