// This file was auto-generated by Fern from our API Definition.

import type * as FernAutopilotTestApi from "../../../index.js";

export interface Movie {
    id: FernAutopilotTestApi.MovieId;
    title: string;
    /** The rating scale out of ten stars */
    rating: number;
    metadata: string;
    rank: number;
}
