// This file was auto-generated by Fern from our API Definition.

import * as FernAutopilotTestApi from "../../src/api/index";
import { FernAutopilotTestApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Imdb", () => {
    test("createMovie", async () => {
        const server = mockServerPool.createServer();
        const client = new FernAutopilotTestApiClient({ environment: server.baseUrl });
        const rawRequestBody = {
            title: "title",
            rating: 1.1,
            metadata: "metadata",
            more_metadata: "more_metadata",
            rank: 1,
            option: "option",
        };
        const rawResponseBody = "string";
        server
            .mockEndpoint()
            .post("/movies/create-movie")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.imdb.createMovie({
            title: "title",
            rating: 1.1,
            metadata: "metadata",
            more_metadata: "more_metadata",
            rank: 1,
            option: "option",
        });
        expect(response).toEqual("string");
    });

    test("getMovie (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernAutopilotTestApiClient({ environment: server.baseUrl });

        const rawResponseBody = {
            id: "tt0111161",
            title: "The Shawshank Redemption",
            rating: 9.3,
            metadata: "hey",
            rank: 1,
        };
        server.mockEndpoint().get("/movies/tt0111161").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.imdb.getMovie("tt0111161");
        expect(response).toEqual({
            id: "tt0111161",
            title: "The Shawshank Redemption",
            rating: 9.3,
            metadata: "hey",
            rank: 1,
        });
    });

    test("getMovie (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernAutopilotTestApiClient({ environment: server.baseUrl });

        const rawResponseBody = "tt1234";
        server.mockEndpoint().get("/movies/tt1234").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.imdb.getMovie("tt1234");
        }).rejects.toThrow(FernAutopilotTestApi.MovieDoesNotExistError);
    });
});
