// This file was auto-generated by Fern from our API Definition.

import { Imdb } from "./api/resources/imdb/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";

export declare namespace FernAutopilotTestApiClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FernAutopilotTestApiClient {
    protected readonly _options: FernAutopilotTestApiClient.Options;
    protected _imdb: Imdb | undefined;

    constructor(_options: FernAutopilotTestApiClient.Options) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "",
                    "X-Fern-SDK-Version": "1.0.1",
                    "User-Agent": "/1.0.1",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get imdb(): Imdb {
        return (this._imdb ??= new Imdb(this._options));
    }
}
